[package]
name = "nnn-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
toml_edit = { version = "0.13.4" }
pancurses = { version = "0.17.0" }
